### PR TITLE
Allow aggregation functions in node_distance_from/to

### LINKED ISSUE #26: distance from leaf is not working
I think there's an error in `node_distance_from()`, as it returns wrong results when applied to `node_is_leaf()`. Here's an example:

```
library(tidygraph)

graph <- create_tree(20,2, directed = TRUE, mode="in") %>% 
  activate(nodes) %>% mutate(name=1:n())
```
The following code returns:

```
graph %>% 
  mutate(dist = node_distance_from(node_is_leaf())) %>% 
  as_tibble() %>% head

# A tibble: 20 x 2
    name  dist
   <int> <dbl>
 1     1     3
 2     2   Inf
 3     3     2
 4     4   Inf
 5     5   Inf
 6     6   Inf
```
While it should return:
```
# A tibble: 20 x 2
    name  dist
   <int> <dbl>
 1     1     3
 2     2     2
 3     3     2
 4     4     2
 5     5     1
 6     6     1
```

The way to fix it is in the file [pair_measures.R](https://github.com/thomasp85/tidygraph/blob/master/R/pair_measures.R) (line 132) replace:
`  unlist(Map(function(s, t) {dist[s, t]}, s = match(source, source_unique), t = target))`
with:
`  unlist(Map(function(s, t) {min(dist[ , t])}, s = match(source, source_unique), t = target))`

Not sure what was the intention of "diagonal" picking from matrix, but here we are actually interested in minimum distance from all sources to each individual target.

### PR DESCRIPTION
**Pull request by dmi3kno**
Closes #26

### CODE REVIEW

**Comment by thomasp85** [comment]
I'm unsure what the use of this is for? Can you describe your intended use case in more detail than provided in #26?

In general the `node_distance_[from|to]()` functions are intended for calculating the distance between node pairs, not some statistic on the distance distribution to all nodes...

**Comment by dmi3kno** [comment]
Currently `node_distance_[from|to](nodes, mode, weights, algorithm)` allow supplying node_type functions and therefore often used with `node_is_root()`) that is guaranteed to return single node. The function is relying on recycling without validating (or warning) whether such recycling makes sense. 

What I am proposing is that the default behavior of the node_distance_[from|to]() should be aggregation, unless user stipulates otherwise. In fact, calculating distance to single node is a particular example of an "identity" aggregation.

Let's say user wants to see how far is the node from center of the network using `node_is_center()`. If by any chance two nodes share same eccentricity, distance function will return meaningless results. However, if central nodes are close to each other, returning average of individual distances to those nodes might still make sense (central nodes are likely to be close to each other).

In my use case I needed to check the minimum distance to leaves in the tree to measure the node "hierarchy level". Again, I was interested in aggregation using min(), but other function might also make sense.

You may argue that the function that I am after shall be called `node_distance_[from|to]_summarise()`.

**Comment by thomasp85** [comment]
I will definitely not repurpose the node pair functions to return summaries. I do see and understand your use case but I’ll need a bit more time to think about the best API for it

**Comment by dmi3kno** [comment]
Happy to discuss further and, once agreed on the vision, contribute PR. God Jul! 🎄

**Pull request closed without merging**
